// Generates validation/lib/validators.generated.ts: the JSON Schema validators,
// compiled ahead of time with Ajv's standalone mode.
//
// Why: Ajv normally compiles validators at runtime with `new Function`, which
// runtimes that forbid code generation refuse (Cloudflare Workers, strict CSP).
// Compiled ahead of time, the same validators run anywhere, and the package
// still ships one validator, not a copy per runtime.
//
//   npm run build:validators            regenerate
//   npm test                            fails if the committed file is stale

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import AjvModule from 'ajv/dist/2020.js'
import formatsModule from 'ajv-formats'
import standaloneModule from 'ajv/dist/standalone/index.js'
import specJson from '../SPEC.schema.json' with { type: 'json' }
import summaryJson from '../SPEC.summary.schema.json' with { type: 'json' }
import recordJson from '../record.schema.json' with { type: 'json' }

const interop = <T,>(mod: T): T => ((mod as { default?: T }).default ?? mod)
const Ajv2020 = interop(AjvModule.default)
const addFormats = interop(formatsModule.default)
const standaloneCode = interop(standaloneModule.default)

export const GENERATED_PATH = fileURLToPath(new URL('./lib/validators.generated.ts', import.meta.url))

/** The Ajv options the validator has always used, plus source output for standalone code. */
export function generateValidators(): string {
  const ajv = new Ajv2020({
    strict: true,
    strictTypes: false,
    strictRequired: false,
    allErrors: true,
    allowUnionTypes: true,
    code: { source: true, esm: true },
  })
  addFormats(ajv)
  ajv.addSchema(specJson)
  ajv.addSchema(summaryJson)
  ajv.addSchema(recordJson)
  const recordId = (recordJson as { $id: string }).$id
  let code: string = standaloneCode(ajv, {
    full: (specJson as { $id: string }).$id,
    summary: (summaryJson as { $id: string }).$id,
    record: recordId,
    adoption: `${recordId}#/$defs/Adoption`,
  })

  // Ajv's ESM output still calls require() for its runtime helpers. Turn each
  // into an import, resolving CommonJS defaults the way Node and bundlers differ.
  const runtime = new Set<string>()
  code = code.replace(/require\("ajv\/dist\/runtime\/([a-z0-9]+)"\)\.default/g, (_m, name: string) => {
    runtime.add(name)
    return `__fn(__rt_${name})`
  })
  code = code.replace(/require\("ajv-formats\/dist\/formats"\)\.fullFormats/g, '__fullFormats')
  if (/require\(/.test(code)) throw new Error('unhandled require() in generated validators')
  if (/new Function|eval\(/.test(code)) throw new Error('generated validators still generate code at runtime')

  const header = [
    '// @ts-nocheck',
    '/* eslint-disable */',
    '// GENERATED by validation/build-validators.ts from SPEC.schema.json, SPEC.summary.schema.json',
    '// and record.schema.json. Do not edit: run `npm run build:validators`.',
    ...[...runtime].sort().map((name) => `import * as __rt_${name} from "ajv/dist/runtime/${name}.js"`),
    'import * as __formats from "ajv-formats/dist/formats.js"',
    'const __fn = (ns) => (typeof ns.default === "function" ? ns.default : ns.default.default)',
    'const __fullFormats = __formats.fullFormats ?? __formats.default.fullFormats',
    '',
  ].join('\n')
  return `${header}${code.replace(/^"use strict";?/, '')}\n`
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(GENERATED_PATH, generateValidators())
  console.log(`wrote ${GENERATED_PATH}`)
}
